apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPNAME}-template
labels:
  template: ${APPNAME}-template
  app: ${APPNAME}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: ${IMAGENAME}:${TAG}
      name: ${TAG}
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPNAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    revisionHistoryLimit: 3
    selector:
      app: ${APPNAME}
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 60
    template:
      metadata:
        labels:
          app: ${APPNAME}
      spec:
        containers:
        - name: ${APPNAME}
          env:
          - name: TZ
            value: Europe/Zurich
          - name: STORAGE_SERVICE
            value: s3
          - name: WORK_DIRECTORY
            value: /ch.so.agi.ilivalidator
          - name: JOBRUNR_WORKER_COUNT
            value: '1'
          envFrom:
          - secretRef:
              name: ${APPNAME}-aws-secret
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          volumeMounts:
          - mountPath: /tmp
            name: ${APPNAME}-tmp-volume
        volumes:
        - emptyDir: {}
          name: ${APPNAME}-tmp-volume
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPNAME}
        from:
          kind: ImageStreamTag
          name: ${APPNAME}:${TAG}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPNAME}
  spec:
    selector:
      app: ${APPNAME}
    ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPNAME}-dashboard
  spec:
    selector:
      app: ${APPNAME}
    ports:
    - protocol: TCP
      name: dashboard
      port: 80
      targetPort: 8000
parameters:
  - name: APPNAME
    description: Name of the App
    required: true
  - name: IMAGENAME
    description: Name of the docker image (e.g. sogis/my-image)
    required: true
  - name: TAG
    description: The docker image to use (e.g. latest)
    required: true
  - name: IMPORT_POLICY_SCHEDULED
    description: Regularly check for changed image?
    required: true
  - name: REPLICA_COUNT
    description: Number of replicas to run
    required: true
  - name: CPU_LIMIT
    description: The maximum amount of CPU the container is allowed to use when running.
    required: true
  - name: MEMORY_LIMIT
    description: The maximum amount of memory the container is allowed to use when running.
    required: true
  - name: CPU_REQUEST
    description: The minimum amount of CPU the container is guaranteed.
    required: true
  - name: MEMORY_REQUEST
    description: The minimum amount of memory the container is guaranteed.
    required: true
