apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPNAME}-template
labels:
  template: ${APPNAME}-template
  app: ${APPNAME}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/${IMAGENAME}:${TAG}
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
      name: ${TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPNAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    selector:
      app: ${APPNAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPNAME}
      spec:
        containers:
        - name: ${APPNAME}
          env: ## List the necessary envirionment variables below
          - name: CCC_MAX_INACTIVITY
            value: '43200'
          - name: CCC_DEBUG
            value: '1'
          ## Define HealthChecks. Ideally the timeoutSeconds for the readiness Probe should be shorter than for the liveness Probe or you have different Probes for the checks
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ## Define the desired Resources for your container. They should be different in test, int and prod environment
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPNAME}
        from:
          kind: ImageStreamTag
          name: ${APPNAME}:${TAG}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPNAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPNAME}
## DELETE IF NOT NEEDED! Define Route only necessary when used with other URL then geo.so.ch
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APPNAME}
  spec:
    host: ${HOSTNAME}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APPNAME}
parameters:
- name: APPNAME
  description: "Name of the App"
  required: true
- name: IMAGENAME
  description: "Name of the docker image"
  required: true
- name: TAG
  description: "The Docker image tag to use (e.g. latest)"
  value: latest
- name: IMPORT_POLICY_SCHEDULED
  description: "Regularly check for changed image?"
  value: "false"
- name: REPLICA_COUNT
  description: "Number of replicas to run"
  value: "1"
- name: HOSTNAME
  description: "The hostname for the route"
- name: CPU_REQUEST
  description: "The minimum amount of CPU the container is guaranteed."
- name: CPU_LIMIT
  description: "The maximum amount of CPU the container is allowed to use when running."
- name: MEMORY_REQUEST
  description: "The minimum amount of memory the container is guaranteed."
- name: MEMORY_LIMIT
  description: "The maximum amount of memory the container is allowed to use when running."
