jobs:
  - script: |
      job('gretl_job_generator') {
        description('Generates a Jenkins job for every GRETL-Job found in the Git repository')
        logRotator(-1, 14)
        scm {
          git {
            remote {
              url('${GRETL_JOB_REPO_URL}')
            }
            branch('*/main')
          }
        }
        triggers {
          cron('H H/8 * * *')
        }
        steps {
          dsl {
            external('gretl_job_generator.groovy')
            removeAction('DELETE')
          }
        }
      }
