apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPNAME}-template
labels:
  name: ${APPNAME}-template
  app: ${APPNAME}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: ${IMAGENAME}:${TAG}
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
      name: ${TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPNAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    revisionHistoryLimit: 3
    selector:
      app: ${APPNAME}
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 60
    template:
      metadata:
        labels:
          app: ${APPNAME}
      spec:
        containers:
        - name: ${APPNAME}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ${SPRING_PROFILES_ACTIVE}
          readinessProbe:
            httpGet:
              path: /actuator/health/readinessState
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/livenessState
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
    triggers:
    - type: ConfigChange
    - type: ImageChange  
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPNAME}
        from:
          kind: ImageStreamTag
          name: ${APPNAME}:${TAG}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPNAME}
  spec:
    ports:
    - protocol: TCP
      name: 80-tcp
      port: 80
      targetPort: 8080
    selector:
      app: ${APPNAME}
parameters:
  - name: APPNAME
    description: Name of the App
    required: true
  - name: IMAGENAME
    description: Name of the docker image (e.g. sogis/my-image)
    required: true
  - name: TAG
    description: The Docker image tag to use (e.g. latest) 
    required: true
  - name: IMPORT_POLICY_SCHEDULED
    description: Regularly check for changed image?
    required: true
  - name: REPLICA_COUNT
    description: Number of replicas to run
    required: true
  - description: CPU limit
    name: CPU_LIMIT
    required: true
  - description: CPU request
    name: CPU_REQUEST
    required: true
  - description: Memory limit
    name: MEMORY_LIMIT
    required: true
  - description: Memory request
    name: MEMORY_REQUEST
    required: true
  - description: Spring Profile
    name: SPRING_PROFILES_ACTIVE
    required: true
  - description: Config Resource
    name: CONFIG_RESOURCE
    required: true
