apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ili2gpkg-template
  annotations:
    openshift.io/display-name: "All components for AGI Ilivalidator Web Service"
    description: >-
      "Creates all necessary components for the AGI Ilivalidator Web Service"
    openshift.io/long-description: >-
      "Creates all necessary components for the AGI Ilivalidator Web Service"
    tags: "agi,gdi,ilivalidator,java"
    iconClass: icon-java
labels:
  app: ili2gpkg
  createdBy: ili2gpkg-template 
parameters:
  - description: Name for Environment
    name: env
    required: true
    value: test
  - description: Version of Image
    name: version
    required: true
    value:
  - name: CPU_LIMIT
    description: "Set Limit for cpu"
    required: true
  - name: MEMORY_LIMIT
    description: "Set Limit for Memory Usage"
    required: true
  - name: CPU_REQUEST
    description: "Set Request for cpu"
    required: true
  - name: MEMORY_REQUEST
    description: "Set Request for Memory"
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Image Stream of the application
    labels:
      application: ili2gpkg-web-service
    creationTimestamp: null
    generation: 1
    name: ili2gpkg-web-service
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: ili2gpkg-web-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 60
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          application: ili2gpkg-web-service
          deploymentconfig: ili2gpkg-web-service
      spec:
        containers:
        - image: sogis/ili2gpkg-web-service
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ili2gpkg/actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ili2gpkg-web-service
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ili2gpkg/actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: ili2gpkg-web-service-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: ili2gpkg-web-service-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ili2gpkg-web-service
        from:
          kind: ImageStreamTag
          name: ili2gpkg-web-service:${version}
          namespace: agi-apps-${env}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: ili2gpkg-web-service
    annotations:
      description: http port of application
    labels:
      application: ili2gpkg-web-service
  spec:
    selector:
      deploymentconfig: ili2gpkg-web-service
    ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 8080
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ili2gpkg-web-service
    labels:
      application: ili2gpkg-web-service
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/ili2gpkg-web-service:${version}
      name: ${version}
      importPolicy:
        scheduled: true
