apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPNAME}-template
labels:
  template: ${APPNAME}-template
  app: ${APPNAME}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: ${IMAGENAME}:${TAG}
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
      name: ${TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPNAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    revisionHistoryLimit: 3
    selector:
      app: ${APPNAME}
    strategy:
      ## Increase timeoutSeconds if app takes longer to get ready
      type: Rolling
      rollingParams:
        timeoutSeconds: 60
    template:
      metadata:
        labels:
          app: ${APPNAME}
      spec:
        containers:
        - name: ${APPNAME}
          ## List the necessary envirionment variables below
          env:
          - name: INPUT_CONFIG_PATH
            value: /srv/qwc_service/volumes/config-in
          - name: OUTPUT_CONFIG_PATH
            value: /tmp
          - name: SERVICE_UID
            value: www-data
          - name: SERVICE_GID
            value: www-data
          ## Define HealthChecks. Ideally the timeoutSeconds for the readiness Probe should be shorter than for the liveness Probe or you have different Probes for the checks
          readinessProbe:
            httpGet:
              path: /ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          ## Define the required volume mounts
          volumeMounts:
          - name: qgs-resources
            mountPath: /data
          - name: qwc-assets
            mountPath: /qwc2/assets/forms
            subPath: forms
          - name: edit-generator-pg-service
            mountPath: /etc/postgresql
          - name: tenant-config-claim
            mountPath: /srv/qwc_service/volumes/config-in/default
          - name: workspace-volume
            mountPath: /tmp
        ## Define the required volumes
        volumes:
        - name: qgs-resources
          persistentVolumeClaim:
            claimName: qgs-resources-claim
        - name: qwc-assets
          persistentVolumeClaim:
            claimName: qwc-assets-claim
        - emptyDir: {}
          name: workspace-volume
        - name: edit-generator-pg-service
          secret:
            secretName: edit-generator-pg-service-secret
            items:
              - key: pg_service.conf
                path: pg_service.conf
        - name: tenant-config-claim
          configMap:
            name: edit-generator-tenantconfig
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPNAME}
        from:
          kind: ImageStreamTag
          name: ${APPNAME}:${TAG}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPNAME}
  spec:
    ## Define the ports exposed by the app
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 9090
    selector:
      app: ${APPNAME}
## DELETE IF NOT NEEDED! A route is necessary only when using a different URL than geo.so.ch
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APPNAME}
  spec:
    host: ${HOSTNAME}
    port:
      targetPort: 80-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: None
    to:
      kind: Service
      name: ${APPNAME}
parameters:
- name: APPNAME
  description: Name of the App
  required: true
- name: IMAGENAME
  description: Name of the docker image (e.g. sogis/my-image)
  required: true
- name: TAG
  description: The Docker image tag to use (e.g. latest)
  required: true
- name: IMPORT_POLICY_SCHEDULED
  description: Regularly check for changed image?
  required: true
- name: REPLICA_COUNT
  description: Number of replicas to run
  required: true
- name: CPU_REQUEST
  description: The minimum amount of CPU the container is guaranteed.
  required: true
- name: CPU_LIMIT
  description: The maximum amount of CPU the container is allowed to use when running.
  required: true
- name: MEMORY_REQUEST
  description: The minimum amount of memory the container is guaranteed.
  required: true
- name: MEMORY_LIMIT
  description: The maximum amount of memory the container is allowed to use when running.
  required: true
- name: HOSTNAME
  description: The hostname for the route
