apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPNAME}-template
labels:
  template: ${APPNAME}-template
  app: ${APPNAME}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: ${IMAGENAME}:${TAG}
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
      name: ${TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPNAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    revisionHistoryLimit: 3
    selector:
      app: ${APPNAME}
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 60
    template:
      metadata:
        labels:
          app: ${APPNAME}
      spec:
        containers:
        - name: ${APPNAME}
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: ${ENVIRONMENT_SHORT} 
          - name: DATA_SERVICE_URL
            value: https://${URL}.so.ch/api/data/v1/ch.so.agi.av.nachfuehrungsgemeinden.data/
          - name: PDF_MAP_URL
            value: https://${URL}.so.ch/map?hp=ch.so.agi.gemeindegrenzen&hf=%5B%5B%22bfs_gemeindenummer%22%2C%22%3D%22%2C%22{{BFS_NR}}%22%5D%5D
          - name: ITF_SO_BUCKET_NAME
            value: ${ITF_SO_BUCKET_NAME}
          - name: ITF_CH_BUCKET_NAME
            value: ${ITF_CH_BUCKET_NAME}
          - name: DXF_BUCKET_NAME
            value: ${DXF_BUCKET_NAME}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ${APPNAME}-aws-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ${APPNAME}-aws-secret
                key: aws_secret_access_key
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          volumeMounts:
          - mountPath: /tmp
            name: ${APPNAME}-volume-1
        volumes:
        - emptyDir: {}
          name: ${APPNAME}-volume-1
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPNAME}
        from:
          kind: ImageStreamTag
          name: ${APPNAME}:${TAG}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPNAME}
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPNAME}
parameters:
- name: APPNAME
  description: Name of the App
  required: true
- name: IMAGENAME
  description: Name of the docker image (e.g. sogis/my-image)
  required: true
- name: ENVIRONMENT_SHORT
  description: The short name of the environment the template is processed for (one of dev, test, int, prod)
  required: true
- name: TAG
  description: The Docker image tag to use (e.g. latest, 1.0.5)
  required: true
- name: IMPORT_POLICY_SCHEDULED
  description: Regularly check for changed image?
  required: true
- name: REPLICA_COUNT
  description: Number of replicas to run
  required: true
- name: URL
  description: Url of the Environment
  required: true
- name: ITF_SO_BUCKET_NAME
  description: itf SO bucket name (ch.so.agi.av.dm01avso24lv95 for prod and int, ch.so.agi.av.dm01avso24lv95-test for test)
  required: true
- name: ITF_CH_BUCKET_NAME
  description: itf CH bucket name (ch.so.agi.av.dm01avch24lv95d for prod and int, ch.so.agi.av.dm01avch24lv95d-test for test)
  required: true
- name: DXF_BUCKET_NAME
  description: dxf bucket name (ch.so.agi.av.dxfgeobau for prod and int, ch.so.agi.av.dxfgeobau-test for test)
  required: true
- name: CPU_LIMIT
  description: Set Limit for cpu
  required: true
- name: MEMORY_LIMIT
  description: Set Limit for Memory Usage
  required: true
- name: CPU_REQUEST
  description: Set Request for cpu
  required: true
- name: MEMORY_REQUEST
  description: Set Request for Memory
  required: true
