apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPNAME}
  annotations:
    description: "Liberating Analytics. Matomo is the only web and mobile analytics platform that gives you full control over your data and more."
    tags: "analytics,piwik,${APPNAME}"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "tobrunet"
    template.openshift.io/documentation-url: "https://github.com/tobru/piwik-openshift/blob/master/README.md"
    template.openshift.io/support-url: "https://github.com/tobru/piwik-openshift/issues"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPNAME}
    name: ${APPNAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: ${IMAGENAME}:${TAG}
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
      name: ${TAG}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPNAME}
    name: nginx
  spec:
    tags:
    - from:
        kind: DockerImage
        name: nginxinc/nginx-unprivileged:stable
      importPolicy: {}
      name: stable
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPNAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    revisionHistoryLimit: 3
    selector:
      app: ${APPNAME}
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 60
    template:
      metadata:
        labels:
          app: ${APPNAME}
      spec:
        containers:
        - name: ${APPNAME}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          volumeMounts:
          - mountPath: /var/www/html
            name: ${APPNAME}-source
          - mountPath: /var/www/html/misc
            name: app-config
            subPath: misc
          - mountPath: /var/www/html/config
            name: app-config
            subPath: config
        - name: nginx
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          volumeMounts:
          - mountPath: /var/www/html
            name: ${APPNAME}-source
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-config-claim
            subPath: nginx.conf
        volumes:
        - emptyDir: {}
          name: ${APPNAME}-source
        - name: app-config
          persistentVolumeClaim:
            claimName: app-config
        - configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
          name: nginx-config-claim
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPNAME}
        from:
          kind: ImageStreamTag
          name: ${APPNAME}:${TAG}
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - nginx
        from:
          kind: ImageStreamTag
          name: nginx:stable
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPNAME}
    name: ${APPNAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPNAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APPNAME}
  spec:
    host: ${HOSTNAME}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APPNAME}
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${APPNAME}
  spec:
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    concurrencyPolicy: Replace
    jobTemplate:
      spec:
        activeDeadlineSeconds: 3600
        template:
          spec:
            containers:
            - command:
              - bash
              - -c
              - tar cf - --one-file-system -C /usr/src/${APPNAME} . | tar xf - --no-overwrite-dir
                && php -f /var/www/html/console core:archive
              image: ${IMAGENAME}:${TAG}
              imagePullPolicy: Always
              name: cron
              resources: {}
              terminationMessagePath: /dev/termination-log
              volumeMounts:
              - mountPath: /var/www/html/misc
                name: app-config
                subPath: misc
              - mountPath: /var/www/html/config
                name: app-config
                subPath: config
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            securityContext:
              runAsUser: 33
            serviceAccountName: pgwatch2
            terminationGracePeriodSeconds: 30
            volumes:
            - emptyDir: {}
              name: ${APPNAME}-source
            - name: app-config
              persistentVolumeClaim:
                claimName: app-config
    schedule: '05 * * * *'
    suspend: false
- apiVersion: v1
  data:
    nginx.conf: |
      # user www-data;
      worker_processes 1;
      error_log /dev/stdout alert;
      pid /tmp/nginx.pid;

      events {
        worker_connections 1024;
      }

      http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;

        upstream php-handler {
          server localhost:9000;
        }

        server {
          listen *:8080 default_server;
          listen [::]:8080 default_server;
          server_name _;
          access_log /dev/stdout;

          # Docker default IP range
          set_real_ip_from 172.16.0.0/12;
          real_ip_header X-Forwarded-For;

          # Path to the root of your installation
          root /var/www/html/;
          index index.php;

          ## deny access to all other .php files
          location ~* ^.+\.php$ {
              deny all;
              return 403;
          }

          ## serve all other files normally
          location / {
              try_files $uri $uri/ =404;
          }

          ## disable all access to the following directories
          location ~ ^/(config|tmp|core|lang) {
              deny all;
              return 403; # replace with 404 to not show these directories exist
          }
          
          location ~ /\.ht {
              deny  all;
              return 403;
          }

          location ~ js/container_.*_preview\.js$ {
              expires off;
              add_header Cache-Control 'private, no-cache, no-store';
          }

          location ~ \.(gif|ico|jpg|png|svg|js|css|htm|html|mp3|mp4|wav|ogg|avi|ttf|eot|woff|woff2|json)$ {
              allow all;
              ## Cache images,CSS,JS and webfonts for an hour
              ## Increasing the duration may improve the load-time, but may cause old files to show after an Matomo upgrade
              expires 1h;
              add_header Pragma public;
              add_header Cache-Control "public";
          }

          location ~ ^/(libs|vendor|plugins|misc|node_modules) {
              deny all;
              return 403;
          }

          ## properly display textfiles in root directory
          location ~/(.*\.md|LEGALNOTICE|LICENSE) {
              default_type text/plain;
          }

          ## Relay all index.php requests to fastcgi.
          location = /index.php {
              fastcgi_split_path_info ^(.+\.php)(/.*)$;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param PATH_INFO $fastcgi_path_info;
              fastcgi_param HTTPS on;
              fastcgi_param REMOTE_ADDR $http_x_forwarded_for;
              #Avoid sending the security headers twice
              fastcgi_param modHeadersAvailable true;
              fastcgi_param front_controller_active true;
              fastcgi_pass php-handler;
              fastcgi_intercept_errors on;
              fastcgi_request_buffering off;
              ## cache ui for 5m (set the same interval of your crontab)
              #include apps/piwik/fcgi_piwik_cache.conf;
          }

          ## Relay all piwik.php requests to fastcgi.
          location = /piwik.php {
              fastcgi_split_path_info ^(.+\.php)(/.*)$;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param PATH_INFO $fastcgi_path_info;
              fastcgi_param HTTPS on;
              fastcgi_param REMOTE_ADDR $http_x_forwarded_for;
              #Avoid sending the security headers twice
              fastcgi_param modHeadersAvailable true;
              fastcgi_param front_controller_active true;
              fastcgi_pass php-handler;
              fastcgi_intercept_errors on;
              fastcgi_request_buffering off;
              #include apps/piwik/fcgi_piwik_long_cache.conf;
          }

          # Add headers to serve security related headers
          # Before enabling Strict-Transport-Security headers please read into this
          # topic first.
          # add_header Strict-Transport-Security "max-age=15768000;
          #add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
          # includeSubDomains; preload;";
          #
        }
      }
  kind: ConfigMap
  metadata:
    name: nginx-conf
parameters:
- name: APPNAME
  description: Name of the App
  required: true
- name: IMAGENAME
  description: Name of the docker image (e.g. sogis/my-image)
  required: true
- name: TAG
  description: The docker image tag to use (e.g. latest)
  required: true
- name: IMPORT_POLICY_SCHEDULED
  description: Regularly check for changed image?
  required: true
- name: REPLICA_COUNT
  description: Number of the replicas to run
  required: true
- name: CPU_REQUEST
  description: The minimum amount of CPU the container is guaranteed.
  required: true
- name: CPU_LIMIT
  description: The maximum amount of CPU the container is allowed to use when running.
  required: true
- name: MEMORY_REQUEST
  description: The minimum amount of memory the container is guaranteed.
  required: true
- name: MEMORY_LIMIT
  description: The maximum amount of memory the container is allowed to use when running.
  required: true
- name: HOSTNAME
  description: The hostname for the route
  required: true
